import type { CSSProperties } from "react";

const iconMap: Record<string, string> = {
  Loader2: "hourglass_top",
  Upload: "cloud_upload",
  X: "close",
  ZoomIn: "zoom_in",
  ZoomOut: "zoom_out",
  Copy: "content_copy",
  Download: "download",
  Bookmark: "bookmark",
  LayoutGrid: "grid_view",
  FileText: "description",
  ChevronDown: "expand_more",
  ChevronUp: "expand_less",
  LogIn: "login",
  Sun: "light_mode",
  Moon: "dark_mode",
  Send: "send",
  Sparkles: "auto_awesome",
  User: "person",
  Eye: "visibility",
  EyeOff: "visibility_off",
  Trash2: "delete",
  AlertTriangle: "warning",
  RotateCcw: "refresh",
  PanelLeft: "menu",
  LayoutDashboard: "dashboard",
  Users: "people",
  LogOut: "logout",
  Check: "check",
  Plus: "add",
  Minus: "remove",
  Search: "search",
  Settings: "settings",
  Home: "home",
  Info: "info",
  Warning: "warning",
  Error: "error",
  Close: "close",
  Menu: "menu",
  MoreVert: "more_vert",
  ArrowBack: "arrow_back",
  ArrowForward: "arrow_forward",
  ArrowUpward: "arrow_upward",
  ArrowDownward: "arrow_downward",
  Edit: "edit",
  Save: "save",
  Delete: "delete",
  Share: "share",
  Print: "print",
  Help: "help",
  Favorite: "favorite",
  Star: "star",
  PlayArrow: "play_arrow",
  Pause: "pause",
  Stop: "stop",
  Refresh: "refresh",
  Done: "done",
  Clear: "clear",
  FilterList: "filter_list",
  Sort: "sort",
  List: "list",
  ViewModule: "view_module",
  ViewList: "view_list",
  ViewColumn: "view_column",
  Fullscreen: "fullscreen",
  FullscreenExit: "fullscreen_exit",
  AccountCircle: "account_circle",
  Lock: "lock",
  Notifications: "notifications",
};

function MaterialIcon({ icon, className = "", style }: { icon: string; className?: string; style?: CSSProperties }) {
  const mapped = iconMap[icon] || icon;
  return <i className={`material-icons ${className}`} style={style}>{mapped}</i>;
}

export { MaterialIcon, iconMap };
